### ISSUE TITLE
Fatal error: Class 'Request' not found in

### ISSUE THREAD

**Issue by ghost** [XoopsModules26x/xootags#3]
Hello Developers,
I have seen that there is already XOOPS 2.6 modules and wants to test it. When modules XooTags this error message have in the backend:

```
Fatal error: Class 'request' not found in /www/htdocs/xxxxxxxx/cms/xoops26/modules/xootags/admin/footer.php on line 21
```

Can you help me maybe and watch it ?!

Thanks in advance.

**Comment by mambax7** [comment]
Fixed here: https://github.com/XoopsModules26x/xootags/commit/41df31464ef5e0b1776008f0120dd48c0f32876a

Please note that these modules are in "Alpha", i.e. they have bugs and you have to see them as "experimental",  i.e. you have to be able to deal with some of the errors and bugs yourself :)

They are here so other people can learn, but they are not to be deployed on your "production website" :)
